version: '3.8'

services:
  # Backend servisi
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
        - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
        - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db

  # PostgreSQL veritabanı
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=my_spring_app
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Frontend servisi
  frontend:
    build: "C:/Users/Lenovo/OneDrive/Masaüstü/spring_front_app/frontend"
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres-data:
